declare const classNames: {
  readonly app: "app";
  readonly content: "content";
  readonly tabs: "tabs";
  readonly tab: "tab";
  readonly close: "close";
  readonly closeWithChildren: "closeWithChildren";
  readonly active: "active";
  readonly transparent: "transparent";
  readonly noFavicon: "noFavicon";
  readonly volume: "volume";
  readonly title: "title";
  readonly add: "add";
  readonly tabWrapper: "tabWrapper";
  readonly popup: "popup";
  readonly tabTitle: "tabTitle";
  readonly tabUrl: "tabUrl";
  readonly thumbnail: "thumbnail";
  readonly menu: "menu";
};
export = classNames;
